name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

permissions:
  packages: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Get latest tag
        id: latest_tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/gabehf/Koito/tags | jq -r '.[0].name')
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo "KOITO_VERSION=${LATEST_TAG}" >> $GITHUB_ENV
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: gabehf/Koito
          ref: ${{ env.LATEST_TAG }}
          path: Koito

      - name: Use Dockerfile in repo
        run: |
          cp Dockerfile Koito/Dockerfile
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/kreatoo/koito-docker:${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64

      - name: Create and push tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.LATEST_TAG }} || true 
          git push origin ${{ env.LATEST_TAG }} || true
          gh release create ${{ env.LATEST_TAG }} --generate-notes || true
